export const MASTER_ITEM_LIST = [
  "Air pressure",
  "Multihead hopper position",
  "Upper capachos state",
  "Intermediate capachos state",
  "Lower capachos state",
  "Elevator ignition",
  "Multihead atoche sensors",
  "Videojet power",
  "Videojet message or label (Box)",
  "% of ink and disolvent (Box)",
  "Videojet message or label (Bag)",
  "% of ink and disolvent (Bag)",
  "Equipment ignition",
  "Bag feed clamp",
  "Suction and singularization of bags",
  "Conveyor clamp",
  "Bag encoder",
  "Initial bag opening",
  "Air pulse",
  "Bag opening",
  "Bag filling",
  "Sealing bar 1",
  "Sealing bar 2",
  "Heater on (T°)",
  "Bag unloading"
] 